# -*- coding: utf-8 -*-
"""game_rpg.py.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o9NxE36FpcVQY9LP8MiSY6XQ3U0LpF5F
"""

class Hero:
  # Constructor: Dijalankan saat Hero baru dibuat
  def __init__(self, name, hp, attack_power):
    self.name = name # Nama Hero
    self.hp = hp # Nyawa (Health Point)
    self.attack_power = attack_power # Kekuatan Serangan
  # Method untuk menampilkan info hero
  def info(self):
    print(f"Hero: {self.name}| HP: {self.hp} | Power:  {self.attack_power}")
# -- Main Program --
# Membuat Object (Instansiasi)
hero1 = Hero("Layla", 100, 15)
hero1.hp = 500
hero2 = Hero("Zilong", 120, 20)
# Memanggil Method
hero1.info()
hero2.info()

"""variabel yang awalnya 100 akan berubah menjadi 500"""

class Hero:
    def __init__(self, name, hp, attack_power):
        self.name = name
        self.hp = hp
        self.attack_power = attack_power

    # Method menyerang: Objek ini (self) menyerang objek lain (lawan)
    def serang(self, lawan):
        print(f"{self.name} menyerang {lawan.name}!")
        lawan.diserang(self.attack_power)

    # Method diserang: Menerima damage
    def diserang(self, damage):
        self.hp -= damage
        print(f"{self.name} terkena damage {damage}. Sisa HP: {self.hp}")


# Membuat objek
hero1 = Hero("Layla", 100, 20)
hero2 = Hero("Zilong", 120, 15)

# Tambah kode Output di akhir program
print("\n--- Pertarungan Dimulai ---")
hero1.serang(hero2)  # Layla menyerang Zilong
hero2.serang(hero1)  # Zilong membalas

"""Parameter `lawan` menerima objek utuh karena method `serang` perlu memanggil `lawan.diserang()` dan mengakses `lawan.hp`. Kalau cuma dikirim string nama, method tersebut tidak bisa dipanggil sehingga akan error. Makanya harus dikirim objeknya, supaya antar objek bisa saling berkomunikasi."""

class Hero:
    def __init__(self, name, hp, attack_power):
        self.name = name
        self.hp = hp
        self.attack_power = attack_power

    def serang(self, lawan):
        print(f"{self.name} menyerang {lawan.name}!")
        lawan.diserang(self.attack_power)

    def diserang(self, damage):
        self.hp -= damage
        print(f"{self.name} terkena damage {damage}. Sisa HP: {self.hp}")


# Class Mage adalah anak dari class Hero
class Mage(Hero):
    def __init__(self, name, hp, attack_power, mana):
        # Memanggil constructor milik Parent (Hero)
        super().__init__(name, hp, attack_power)
        self.mana = mana

    def info(self):
        print(f"{self.name} [Mage] | HP: {self.hp} | Mana: {self.mana}")

    # Mage punya skill khusus
    def skill_fireball(self, lawan):
        if self.mana >= 20:
            print(f"{self.name} menggunakan Fireball ke {lawan.name}!")
            self.mana -= 20
            lawan.diserang(self.attack_power * 2)  # Damage 2x lipat
        else:
            print(f"{self.name} gagal skill! Mana tidak cukup.")


# -- Main Program Baru --
print("\n--- Update Class Hero ---")
eudora = Mage("Eudora", 80, 30, 100)
balmond = Hero("Balmond", 200, 10)

eudora.info()
eudora.serang(balmond)          # Serangan biasa (warisan dari Hero)
eudora.skill_fireball(balmond)  # Skill khusus Mage

"""Tugas Analisis 3:

Errornya: `AttributeError: 'Mage' object has no attribute 'name'`

Soalnya `self.name`, `self.hp`, dan `self.attack_power` itu dibuatnya di dalam `__init__` milik Hero, bukan di `Mage`. Nah `super().__init__()` itu tugasnya manggil `__init__` milik Hero, biar atribut-atribut tadi ikut kebuat.

Karena baris `super().__init__()` dihapus, `__init__` Hero jadi nggak pernah dijalankan, jadinya atribut `name`, `hp`, sama `attack_power` nggak pernah kebuat di objek eudora. Yang berhasil kebuat cuma `mana` doang, soalnya itu satu-satunya yang ditulis langsung di `__init__` milik Mage.

Jadi walaupun nama "Eudora" udah dikirim pas bikin objek, nilainya cuma numpang lewat doang, nggak pernah disimpan jadi atribut — makanya errornya "no attribute 'name'".
"""

class Hero:
    def __init__(self, nama, hp_awal):
        self.nama = nama
        # Enkapsulasi: HP bersifat Private (hanya bisa diakses di dalam class ini)
        self.__hp = hp_awal

    # GETTER: Cara resmi melihat HP
    def get_hp(self):
        return self.__hp

    # SETTER: Cara resmi mengubah HP (dengan validasi)
    def set_hp(self, nilai_baru):
        if nilai_baru < 0:
            self.__hp = 0  # HP tidak boleh negatif
        elif nilai_baru > 1000:
            print("Cheat terdeteksi! HP dimaksimalkan ke 1000 saja.")
            self.__hp = 1000
        else:
            self.__hp = nilai_baru

    def diserang(self, damage):
        # Kita pakai setter/getter bahkan di dalam class sendiri agar aman
        sisa_hp = self.get_hp() - damage
        self.set_hp(sisa_hp)
        print(f"{self.nama} terkena damage {damage}. Sisa HP: {self.get_hp()}")


# -- Uji Coba --
hero1 = Hero("Layla", 100)

# hero1.__hp = 9999     # GAGAL (Tidak akan mengubah hp asli)
# print(hero1.__hp)     # ERROR (Tidak bisa dibaca langsung)

hero1.set_hp(-50)          # Coba set negatif
print(hero1.get_hp())      # Output: 0 (Karena dicegat oleh logika Setter)

# ================================
# TUGAS ANALISIS 4 - Bagian 1: Percobaan Hacking
# ================================
print(f"Mencoba akses paksa: {hero1._Hero__hp}")

"""### 1. Percobaan Hacking (`hero1._Hero__hp`)

Nilai HP tetap muncul karena Python menggunakan **Name Mangling**, sehingga `__hp` bisa diakses melalui `_Hero__hp`. Namun, cara ini tidak sebaiknya digunakan karena melewati validasi `set_hp()` dan bisa membuat kode bermasalah jika atribut diubah.

### 2. Uji Validasi

Jika validasi `if/elif` dihapus, `hero1.set_hp(-100)` akan membuat HP menjadi -100. Ini menunjukkan bahwa **Setter penting untuk memvalidasi data** agar nilai yang dimasukkan tetap sesuai dan masuk akal.

"""

from abc import ABC, abstractmethod
class GameUnit(ABC):
    @abstractmethod
    def serang(self, target):
        pass

    @abstractmethod
    def info(self):
        pass
class Hero(GameUnit):

    def __init__(self, nama):
        self.nama = nama
    def serang(self, target):
        print(f"Hero {self.nama} menebas {target}!")
    def info(self):
        print(f"Saya adalah Hero: {self.nama}")


class Monster(GameUnit):
    def __init__(self, jenis):
        self.jenis = jenis
    def serang(self, target):
        print(f"Monster {self.jenis} menggigit {target}!")
    def info(self):
        print(f"Saya adalah Monster: {self.jenis}")

h = Hero("Alucard")
m = Monster("Serigala")

h.info()
m.info()

"""### 1. Hapus method `serang` di Hero

Program akan error karena `Hero` belum memiliki method `serang` yang diwajibkan oleh `GameUnit` sebagai abstract class. Akibatnya, objek `Hero` tidak bisa dibuat.

### 2. Aktifkan `unit = GameUnit()`

Program akan error karena `GameUnit` adalah abstract class, jadi tidak bisa langsung dibuat menjadi objek. Fungsinya sebagai **aturan dasar** untuk class turunannya seperti `Hero` dan `Monster`, agar semuanya memiliki method `serang` dan `info`.

"""

class Hero:
    def __init__(self, nama):
        self.nama = nama
    def serang(self):
        print("Hero menyerang dengan tangan kosong.")
class Mage(Hero):
    def serang(self):
        print(f"{self.nama} (Mage) menembakkan Bola Api! Boom!")

class Archer(Hero):
    def serang(self):
        print(f"{self.nama} (Archer) memanah dari jauh! Jleb!")
class Fighter(Hero):

    def serang(self):
        print(f"{self.nama} (Fighter) memukul dengan pedang! Slash!")
pasukan = [
    Mage("Eudora"),
    Archer("Miya"),
    Fighter("Zilong"),
    Mage("Gord")
]
print("--- PERANG DIMULAI ---")
for pahlawan in pasukan:
    pahlawan.serang()

"""### 1. Uji Skalabilitas

Program tetap berjalan tanpa error meskipun ditambah class `Healer`, dan looping tidak perlu diubah. Ini adalah keuntungan **polimorfisme** karena kita bisa menambah karakter baru tanpa mengubah kode utama.

### 2. Konsistensi Penamaan

Jika method `serang` di `Archer` diganti menjadi `tembak_panah`, program akan error karena looping tetap memanggil `pahlawan.serang()`. Jadi, nama method pada Parent dan Child harus sama agar semua objek bisa dipanggil dengan cara yang sama.

"""