# -*- coding: utf-8 -*-
"""MyEdotel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vIKagwmIm4bzfgyBJOtTV6gnKifOOjZv
"""

from abc import ABC, abstractmethod
class KamarHotel(ABC):
    def __init__(self, nama_kamar, stok, harga_dasar):
        self.nama_kamar = nama_kamar
        # Encapsulation: Atribut Private
        self.__stok = 0
        self.__harga_dasar = harga_dasar
        self.set_stok(stok)

    def get_stok(self):
        return self.__stok

    def set_stok(self, jumlah):
        if jumlah < 0:
            print(f"Gagal update stok {self.nama_kamar}! Stok tidak boleh negatif ({jumlah}).")
        else:
            self.__stok = jumlah
            print(f"Berhasil menambahkan stok {self.nama_kamar}: {self.__stok} unit.")

    def get_harga_dasar(self):
        return self.__harga_dasar


    @abstractmethod
    def tampilkan_detail(self):
        pass

    @abstractmethod
    def hitung_harga_total(self, jumlah_malam):
        pass

class KamarDeluxe(KamarHotel):
    def __init__(self, nama_kamar, stok, harga_dasar, fasilitas):
        super().__init__(nama_kamar, stok, harga_dasar)
        self.fasilitas = fasilitas

    def hitung_harga_total(self, jumlah_malam):
        pajak_per_malam = self.get_harga_dasar() * 0.10
        total_per_malam = self.get_harga_dasar() + pajak_per_malam
        return total_per_malam * jumlah_malam

    def tampilkan_detail(self, jumlah_malam):
        pajak = int(self.get_harga_dasar() * 0.10)
        subtotal = int(self.hitung_harga_total(jumlah_malam))
        print(f"[DELUXE] {self.nama_kamar} | Fasilitas: {self.fasilitas}")
        print(f"   Harga Dasar/Malam: Rp {self.get_harga_dasar():,} | Pajak(10%): Rp {pajak:,}")
        print(f"   Menginap: {jumlah_malam} malam | Subtotal: Rp {subtotal:,}".replace(',', '.'))


class KamarStandard(KamarHotel):
    def __init__(self, nama_kamar, stok, harga_dasar, kapasitas):
        super().__init__(nama_kamar, stok, harga_dasar)
        self.kapasitas = kapasitas

    def hitung_harga_total(self, jumlah_malam):
        pajak_per_malam = self.get_harga_dasar() * 0.05
        total_per_malam = self.get_harga_dasar() + pajak_per_malam
        return total_per_malam * jumlah_malam

    def tampilkan_detail(self, jumlah_malam):
        pajak = int(self.get_harga_dasar() * 0.05)
        subtotal = int(self.hitung_harga_total(jumlah_malam))
        print(f"[STANDARD] {self.nama_kamar} | Kapasitas: {self.kapasitas}")
        print(f"   Harga Dasar/Malam: Rp {self.get_harga_dasar():,} | Pajak(5%): Rp {pajak:,}")
        print(f"   Menginap: {jumlah_malam} malam | Subtotal: Rp {subtotal:,}".replace(',', '.'))

def proses_transaksi(daftar_pesanan):
    print("--- STRUK PEMESANAN ---")
    total_tagihan = 0

    for idx, (kamar, malam) in enumerate(daftar_pesanan, start=1):
        print(f"{idx}. ", end="")
        kamar.tampilkan_detail(malam)
        total_tagihan += kamar.hitung_harga_total(malam)

    print("-" * 40)
    print(f"TOTAL TAGIHAN: Rp {int(total_tagihan):,}".replace(',', '.'))
    print("-" * 40)

if __name__ == "__main__":
    print("--- SETUP DATA KAMAR ---")
    deluxe1 = KamarDeluxe("Kamar Deluxe Sea View", 10, 1500000, "Private Pool")

    standard1 = KamarStandard("Kamar Standard Superior", -5, 500000, "2 Orang")

    standard1.set_stok(20)
    print()
    pesanan_tamu = [
        (deluxe1, 2),
        (standard1, 1)
    ]

    proses_transaksi(pesanan_tamu)